### ISSUE TITLE
检测

### ISSUE THREAD

**Issue by liulingfeng123** [zha0ming1e/cube_slam_modified#1]
您好，这个可以检测任意物体或者图片吗？

**Comment by zha0ming1e** [comment]
Hello, it depends on the object detection front-end, more details in `preprocessing/` and YOLO configurations.

**Comment by liulingfeng123** [comment]
Thanks for your reply, can I add you as a friend for further consultation? My contact information: qq: 1104179308&nbsp;weixin：17854573818.&nbsp;Looking forward to your reply.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zha0ming1e/cube_slam_modified"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月28日(星期六) 晚上6:49
收件人:&nbsp;"zha0ming1e/cube_slam_modified"<cube_slam_modified@noreply.github.com&gt;;
抄送:&nbsp;"刘凌风"<1104179308@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zha0ming1e/cube_slam_modified] 检测 (#1)





 
Hello, it depends on the object detection front-end, more details in preprocessing/ and YOLO configurations.
